### PR TITLE
Added support for 'No More Room in Hell'

### LINKED ISSUE #41: Please support "No More Room in Hell"
Objectives was removed from .vmf file after decompile

### PR DESCRIPTION
**Pull request by gitRihi**
## This PR adds support for the game [No More Room in Hell](https://store.steampowered.com/app/224260/No_More_Room_in_Hell/).

This inculdes:
- Basic detection of the game via file pattern and entitiy type recognizen.
- Decompiling of .nmo files used for objective game mode. Information is automatically written to the vmf and to a nmos. See [https://wiki.nomoreroominhell.com/Objectives_Setup](https://wiki.nomoreroominhell.com/Objectives_Setup) for more information.

### Noteable changes:
For automatic game detection, I updated the appdb.xml located at `resources/info/ata4/bsplib/app` (670bd6e4). However, I also **deleted** another appdb.xml located at `java/info/ata4/bsplib/app`, which was outdated and **seemed** to have no use (b6f9097d). Compilation and execution still worked fine without it.

While implementing .nmo/.nmos files for the class `BspFileEntry`, I also made some minor syntax changes to it (ae7ea248). Additionally, I fixed that the pak directory was not properly changed when using cli (4fe0b9fe).

Objectives in No More Room in Hell are indicated by certain visgroups. These visgroups are nested under one another and create a certain hierarchy. `VmfMeta` previously didn't support writing of nested visgroups. I implemented this feature with 1fed321f.
Nested visgroups can be indicated by separating their names with `/`. For example, `a/b/c` denotes visgroup c, which is in visgroup b, which is in visgroup a. The `/` charcter is also saved in `VmfMeta.VISGROUP_SETPERATOR` which should be the prefered way of nesting visgroups (`a + VmfMeta.VISGROUP_SETPERATOR + b + ...`).

Fixes #41

### CODE REVIEW

**Comment by ata4** [comment]
LGTM. I've merged this one and all your other PRs as well while I'm at it. Sorry that it took so long.

**Comment by gitRihi** [comment]
Hey, thanks for merging my pull requests. :)
I think it would also make sense to release a new version with all these changes. There have been so many since last version 1.3.24, which normal users can't really benefit from, because there are no compiled binaries.

**Comment by ata4** [comment]
Yeah, makes sense. I'll need to reinstall my Java environment first, though. 😄

**Comment by gitRihi** [comment]
Thanks! Yeah, the Java environment will probably be usefull for doing that. 😁

**Pull request merged**
